-- MySQL Script generated by MySQL Workbench
-- Thu Nov 28 11:20:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8 ;
USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optica`.`address` ;

CREATE TABLE IF NOT EXISTS `optica`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `address_street` VARCHAR(45) NULL,
  `address_num` INT NULL,
  `address_unit` INT NULL,
  `address_city` VARCHAR(45) NULL,
  `address_postcode` INT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`providers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optica`.`providers` ;

CREATE TABLE IF NOT EXISTS `optica`.`providers` (
  `providers_id` INT NOT NULL AUTO_INCREMENT,
  `providers_name` VARCHAR(45) NULL,
  `providers_address_id` INT NULL,
  `providers_phone` INT(9) NULL,
  `providers_fax` INT(9) NULL,
  `providers_NIF` VARCHAR(9) NULL,
  PRIMARY KEY (`providers_id`),
  INDEX `fk_providers_address_idx` (`providers_address_id` ASC) VISIBLE,
  CONSTRAINT `fk_providers_address`
    FOREIGN KEY (`providers_address_id`)
    REFERENCES `optica`.`address` (`address_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`brand_name`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optica`.`brand_name` ;

CREATE TABLE IF NOT EXISTS `optica`.`brand_name` (
  `brand_id` INT NOT NULL AUTO_INCREMENT,
  `brand_providers_id` INT NOT NULL,
  `brand_name` VARCHAR(45) NULL,
  PRIMARY KEY (`brand_id`),
  INDEX `fk_brand_providers1_idx` (`brand_providers_id` ASC) VISIBLE,
  CONSTRAINT `fk_brand_providers1`
    FOREIGN KEY (`brand_providers_id`)
    REFERENCES `optica`.`providers` (`providers_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`glasses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optica`.`glasses` ;

CREATE TABLE IF NOT EXISTS `optica`.`glasses` (
  `glasses_id` INT NOT NULL AUTO_INCREMENT,
  `glasses_brand` INT NULL,
  `glasses_graduation_left` INT(25) NULL,
  `glasses_graduation_right` INT(25) NULL,
  `glasses_frame` SET('floating', 'acetate', 'metallic') NULL,
  `glasses_lens_left_color` VARCHAR(45) NULL,
  `glasses_lens_right_color` VARCHAR(45) NULL,
  `glasses_price` DECIMAL(7,2) NULL,
  PRIMARY KEY (`glasses_id`),
  INDEX `fk_glasses_brand_idx` (`glasses_brand` ASC) VISIBLE,
  CONSTRAINT `fk_glasses_brand`
    FOREIGN KEY (`glasses_brand`)
    REFERENCES `optica`.`brand_name` (`brand_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optica`.`clients` ;

CREATE TABLE IF NOT EXISTS `optica`.`clients` (
  `clients_id` INT NOT NULL AUTO_INCREMENT,
  `clients_name` VARCHAR(45) NULL,
  `clients_adress_id` INT NULL,
  `clients_phone` INT(9) NULL,
  `clients_email` VARCHAR(70) NULL,
  `clients_recommender` INT NULL,
  PRIMARY KEY (`clients_id`),
  INDEX `fk_clients_address1_idx` (`clients_adress_id` ASC) VISIBLE,
  INDEX `fk_clients_clients1_idx` (`clients_recommender` ASC) VISIBLE,
  CONSTRAINT `fk_clients_address`
    FOREIGN KEY (`clients_adress_id`)
    REFERENCES `optica`.`address` (`address_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_clients_clients`
    FOREIGN KEY (`clients_recommender`)
    REFERENCES `optica`.`clients` (`clients_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `optica`.`sales` ;

CREATE TABLE IF NOT EXISTS `optica`.`sales` (
  `sales_id` INT NOT NULL AUTO_INCREMENT,
  `sales_register_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `sales_seller` VARCHAR(45) NULL,
  `sales_client` INT NULL,
  `sales_glasses` INT NULL,
  PRIMARY KEY (`sales_id`),
  INDEX `fk_glasses_sales_idx` (`sales_glasses` ASC) VISIBLE,
  INDEX `fk_clients_sales_idx` (`sales_client` ASC) VISIBLE,
  CONSTRAINT `fk_clients_sales`
    FOREIGN KEY (`sales_client`)
    REFERENCES `optica`.`clients` (`clients_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_glasses_sales`
    FOREIGN KEY (`sales_glasses`)
    REFERENCES `optica`.`glasses` (`glasses_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
