-- MySQL Script generated by MySQL Workbench
-- Thu Nov 28 11:18:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pizzeria` ;

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`provinces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`provinces` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`provinces` (
  `provinces_id` INT NOT NULL AUTO_INCREMENT,
  `provinces_name` VARCHAR(45) NULL,
  PRIMARY KEY (`provinces_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`cities` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`cities` (
  `cities_id` INT NOT NULL AUTO_INCREMENT,
  `cities_name` VARCHAR(45) NULL,
  `cities_province` INT NULL,
  PRIMARY KEY (`cities_id`),
  INDEX `fk_cities_provinces_idx` (`cities_province` ASC) VISIBLE,
  CONSTRAINT `fk_cities_provinces`
    FOREIGN KEY (`cities_province`)
    REFERENCES `pizzeria`.`provinces` (`provinces_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`clients` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`clients` (
  `clients_id` INT NOT NULL AUTO_INCREMENT,
  `clients_name` VARCHAR(45) NULL,
  `clients_surname1` VARCHAR(45) NULL,
  `clients_surname2` VARCHAR(45) NULL,
  `clients_address` VARCHAR(45) NULL,
  `clients_zip_code` INT(5) NULL,
  `clients_city_id` INT NULL,
  `clients_province_id` INT NULL,
  `clients_phone_number` INT(9) NULL,
  `clients_col` VARCHAR(45) NULL,
  PRIMARY KEY (`clients_id`),
  INDEX `fk_clients_cities_idx` (`clients_city_id` ASC) VISIBLE,
  INDEX `fk_clients_provinces_idx` (`clients_province_id` ASC) VISIBLE,
  CONSTRAINT `fk_clients_cities`
    FOREIGN KEY (`clients_city_id`)
    REFERENCES `pizzeria`.`cities` (`cities_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_clients_provinces`
    FOREIGN KEY (`clients_province_id`)
    REFERENCES `pizzeria`.`provinces` (`provinces_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`restaurants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`restaurants` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`restaurants` (
  `restaurants_id` INT NOT NULL AUTO_INCREMENT,
  `restaurants_address` VARCHAR(70) NULL,
  `restaurants_zip_code` INT(5) NULL,
  `restaurants_city_id` INT NULL,
  `restaurants_province_id` INT NULL,
  PRIMARY KEY (`restaurants_id`),
  INDEX `fk_restaurants_cities_idx` (`restaurants_city_id` ASC) VISIBLE,
  INDEX `fk_clients_provinces_idx` (`restaurants_province_id` ASC) VISIBLE,
  CONSTRAINT `fk_restaurants_cities`
    FOREIGN KEY (`restaurants_city_id`)
    REFERENCES `pizzeria`.`cities` (`cities_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_clients_provinces`
    FOREIGN KEY (`restaurants_province_id`)
    REFERENCES `pizzeria`.`provinces` (`provinces_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`orders` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`orders` (
  `orders_id` INT NOT NULL AUTO_INCREMENT,
  `orders_datetime` DATETIME NULL,
  `orders_type` ENUM('takeout', 'delivery') NULL,
  `orders_total_price` DECIMAL(7,2) NULL,
  `orders_restaurants_id` INT NULL,
  `orders_clients_id` INT NULL,
  PRIMARY KEY (`orders_id`),
  INDEX `fk_orders_restaurants_idx` (`orders_restaurants_id` ASC) VISIBLE,
  INDEX `fk_orders_clients1_idx` (`orders_clients_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_restaurants`
    FOREIGN KEY (`orders_restaurants_id`)
    REFERENCES `pizzeria`.`restaurants` (`restaurants_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_clients1`
    FOREIGN KEY (`orders_clients_id`)
    REFERENCES `pizzeria`.`clients` (`clients_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`categories` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`categories` (
  `categories_id` INT NOT NULL AUTO_INCREMENT,
  `categories_name` VARCHAR(70) NULL,
  PRIMARY KEY (`categories_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`products` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`products` (
  `products_id` INT NOT NULL AUTO_INCREMENT,
  `products_name` VARCHAR(45) NULL,
  `products_description` TEXT NULL,
  `products_image` BLOB NULL,
  `products_price` DECIMAL(6,2) NULL,
  `products_type` ENUM("pizza", "burger", "drink") NULL,
  `products_category_id` INT NULL,
  PRIMARY KEY (`products_id`),
  INDEX `category_idx` (`products_category_id` ASC) VISIBLE,
  CONSTRAINT `category`
    FOREIGN KEY (`products_category_id`)
    REFERENCES `pizzeria`.`categories` (`categories_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`employees` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`employees` (
  `employees_id` INT NOT NULL AUTO_INCREMENT,
  `employees_name` VARCHAR(45) NULL,
  `employees_surname1` VARCHAR(45) NULL,
  `employees_surname2` VARCHAR(45) NULL,
  `employees_nif` VARCHAR(9) NULL,
  `employees_phone_number` INT(9) NULL,
  `employees_role` ENUM("delivery", "cook") NULL,
  `employees_restaurants_id` INT NULL,
  PRIMARY KEY (`employees_id`),
  INDEX `fk_employees_restaurants1_idx` (`employees_restaurants_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_restaurants1`
    FOREIGN KEY (`employees_restaurants_id`)
    REFERENCES `pizzeria`.`restaurants` (`restaurants_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`delivered`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`delivered` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`delivered` (
  `delivered_id` INT NOT NULL AUTO_INCREMENT,
  `delivered_by_employee_id` INT NULL,
  `delivered_time` DATETIME NULL,
  `delivered_order_id` INT NULL,
  PRIMARY KEY (`delivered_id`),
  INDEX `fk_order_delivered_idx` (`delivered_order_id` ASC) VISIBLE,
  INDEX `fk_delivered_employees_idx` (`delivered_by_employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_delivered_orders`
    FOREIGN KEY (`delivered_order_id`)
    REFERENCES `pizzeria`.`orders` (`orders_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_delivered_employees`
    FOREIGN KEY (`delivered_by_employee_id`)
    REFERENCES `pizzeria`.`employees` (`employees_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`orders_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria`.`orders_products` ;

CREATE TABLE IF NOT EXISTS `pizzeria`.`orders_products` (
  `orders_products_order_id` INT NOT NULL,
  `orders_products_product_id` INT NOT NULL,
  `orders_products_quantity` INT NULL,
  PRIMARY KEY (`orders_products_order_id`, `orders_products_product_id`),
  INDEX `fk_products_idx` (`orders_products_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders`
    FOREIGN KEY (`orders_products_order_id`)
    REFERENCES `pizzeria`.`orders` (`orders_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_products`
    FOREIGN KEY (`orders_products_product_id`)
    REFERENCES `pizzeria`.`products` (`products_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
